### ISSUE TITLE
Designs for better handling of unstable networks

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea-dash#43]
Right now the exits page contains a ton of info about what exits are up and their status. This info is then updated pretty rapidly. 

The problems is that when networks are unstable entries may show up and go away from this list as Babel invalidates routes, then they may go from red to green as pings fail or succeed and all the exits do this independently all at once. 

The end result is a very confusing sort of Christmas tree in which elements which the user may want to interact with are yanked away or changed under the users cursor. 

The goal here is to design some way to communicate to the user when the network is unstable and clearly indicate that they should check their antenna aiming rather than give them this mess. 

deadline: 10/07/18

**Comment by asoltys** [comment]
This was addressed in the design overhaul
