### ISSUE TITLE
Exit signup process does not return error codes properly

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea-dash#70]
If, during the process of signing up for an exit the router/exit returns a 500 or 400 or other error http code the loading bar just continues spinning. 

There are no designs for an error state, so I'm thinking that we just follow the reset flow when that happens.

**Comment by asoltys** [comment]
Fixed in https://github.com/althea-mesh/althea-dash/commit/e36fb6a98374ee575a53bf00378f5cb6030d5e91
