### ISSUE TITLE
Low/negative balance information

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea-dash#80]
Show negative balance based on the debts endpoint when wallet is below zero. Ask Justin for details.

![image](https://user-images.githubusercontent.com/1335122/56311123-1e700f00-6102-11e9-990f-f94d3f5b9f74.png)

Show recommended minimum deposit amount based on 2x the negative balance (but only when balance is negative)

![image](https://user-images.githubusercontent.com/1335122/56311508-0fd62780-6103-11e9-888e-89907bdbb8f2.png)

Also, slightly related, is a more nuanced free tier bar which starts out by warning about the free tier first with some different copy, and then switches to the free tier copy when the free tier really happens: 

![image](https://user-images.githubusercontent.com/1335122/56311959-039e9a00-6104-11e9-9f18-c244eb509a74.png)

**Comment by asoltys** [comment]
Done by https://github.com/althea-mesh/althea-dash/commit/567c5a29710e491f97864c4a758ab932583af77f
